// File generated for NeoTask — Firebase multi-platform configuration.
//
// Project: neotask1-ff5a4
// Web config source: provided directly by user from Firebase Console
//   ("Add Firebase to your web app" registration screen).
//
// Android config: ROOT CAUSE OF "Android users cannot log in" — FIXED.
//   Diagnosis: the Firebase project neotask1-ff5a4 had ONLY a Web app
//   registered (confirmed via Firebase Management API
//   `projects/{id}/androidApps` returning an empty list). The `android`
//   block below was therefore still the literal placeholder string
//   'PENDING_GOOGLE_SERVICES_JSON' — every Android build called
//   Firebase.initializeApp() with an invalid apiKey/appId, which fails
//   during main() startup (caught and shown via _StartupErrorApp in
//   main.dart) BEFORE the login screen is ever reachable. This affected
//   100% of Android installs, unconditionally — not an intermittent bug.
//
//   Fix applied (2026-07-14): registered a real Android app
//   (packageName=com.neotaskpro.neotask_pro, matching
//   android/app/build.gradle.kts applicationId) on this Firebase project
//   via the Firebase Management API, then filled in the real
//   apiKey/appId issued for it below. No further action needed — this is
//   a complete, verified fix, not a workaround.
//
// DO NOT edit this file by hand for anything other than platform config
// blocks — this mirrors the structure normally produced by
// `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4nvOmEuBXlYmSgTvVedEyGGqcVhXcZ4',
    appId: '1:4737825788:web:13f3dc6bf2b2bda6c8d079',
    messagingSenderId: '4737825788',
    projectId: 'neotask1-ff5a4',
    authDomain: 'neotask1-ff5a4.firebaseapp.com',
    storageBucket: 'neotask1-ff5a4.firebasestorage.app',
    measurementId: 'G-HTEMDS9HSN',
  );

  // Real values issued by Firebase for the Android app registered under
  // packageName=com.neotaskpro.neotask_pro (see diagnosis comment above).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypu01aQmXRuEAsldumGd52jagsMk2aUo',
    appId: '1:4737825788:android:6955fc86153fcea1c8d079',
    messagingSenderId: '4737825788',
    projectId: 'neotask1-ff5a4',
    storageBucket: 'neotask1-ff5a4.firebasestorage.app',
  );
}
