// File generated for NeoTask — Firebase multi-platform configuration.
//
// Project: neotask1-ff5a4
// Web config source: provided directly by user from Firebase Console
//   ("Add Firebase to your web app" registration screen).
// Android config: PENDING — google-services.json has not been provided yet.
//   Once received, extract the following fields from it and fill in the
//   `android` DefaultFirebaseOptions block below:
//     - api_key[0].current_key      -> apiKey
//     - project_info.project_id     -> projectId
//     - project_info.storage_bucket -> storageBucket
//     - project_info.project_number -> messagingSenderId
//     - client[0].client_info.mobilesdk_app_id -> appId
//
// DO NOT edit this file by hand for anything other than filling in the
// android block above — this mirrors the structure normally produced by
// `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4nvOmEuBXlYmSgTvVedEyGGqcVhXcZ4',
    appId: '1:4737825788:web:13f3dc6bf2b2bda6c8d079',
    messagingSenderId: '4737825788',
    projectId: 'neotask1-ff5a4',
    authDomain: 'neotask1-ff5a4.firebaseapp.com',
    storageBucket: 'neotask1-ff5a4.firebasestorage.app',
    measurementId: 'G-HTEMDS9HSN',
  );

  // PENDING: placeholder values below MUST be replaced once
  // android/app/google-services.json is provided by the user.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PENDING_GOOGLE_SERVICES_JSON',
    appId: 'PENDING_GOOGLE_SERVICES_JSON',
    messagingSenderId: '4737825788',
    projectId: 'neotask1-ff5a4',
    storageBucket: 'neotask1-ff5a4.firebasestorage.app',
  );
}
